person:
  name: kk
  age: 18
  happy: true
  birth: 2000/01/01 #必须写规范
  maps: {k1: v1,k2: v2}
  lists:
   - d
   - a
   - c
  dog:
    name: 阿黄
    age:  3





#server:
#  port: 8080
#spring:
#  profiles:
#    active: dev
#
#---
#
#
#server:
#  port: 8081
#spring:
#  profiles: dev
#
#
#---
#server:
#  port: 8082
#spring:
#  profiles: prod

spring:
  jackson:
    date-format:yyyy-MM-dd HH:mm:ss
    time-zone:GMT+8
#  datasource:
#    primary:
#       username: root
#       password: 123456
#       #?serverTimezone=UTC解决时区的报错
#       url: jdbc:mysql://localhost:3306/testdb?characterEncoding=utf-8
#       driver-class-name: com.mysql.jdbc.Driver
#    secondary:
#       username: root
#       password: 123456
#       #?serverTimezone=UTC解决时区的报错
#       url: jdbc:mysql://localhost:3306/testdb2?characterEncoding=utf-8
#       driver-class-name: com.mysql.jdbc.Driver
primarydb:
  uniqueResourceName: primary
  xaDataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
  xaProperties:
    url: jdbc:mysql://192.168.1.91:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    user: root
    password: 123456
  exclusiveConnectionMode: true
  minPoolSize: 3
  maxPoolSize: 10
  testQuery: SELECT 1 from dual #由于采用HikiriCP，用于检测数据库连接是否存活。

secondarydb:
  uniqueResourceName: secondary
  xaDataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
  xaProperties:
    url: jdbc:mysql://localhost:3306/testdb2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    user: root
    password: 123456
  exclusiveConnectionMode: true
  minPoolSize: 3
  maxPoolSize: 10
  testQuery: SELECT 1 from dual #由于采用HikiriCP，用于检测数据库连接是否存活
